logging.level.org.springframework=INFO
server.port=8080

# ===============================
# DataSource / Database
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/teacherdatabase?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Dev26awatef
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
